'use client';
import { useEffect, useRef, useState } from 'react';
import {MaterialControls,emptyMaterial,type MaterialUI} from './material-controls';
import {ProjectLibrary,type ProjectMeta} from './project-library';
import type {BadgeProject} from '@/lib/projects';
import {MovementControls} from './movement-controls';
import {defaultMotion} from '@/lib/animation';
import { Button } from '@/components/ui/button';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { surfaceNames, type Surface } from '@/lib/surfaces';
import { Download, Upload, RotateCcw, Shield, Move3d, ImagePlus } from 'lucide-react';
import type { BadgeEngine, BadgeSettings, ReliefLayer, BadgePick } from '@/lib/badge-engine';
const initial: BadgeSettings = { faceTextureStrength:.5, frameMetal:'gold',frameSurface:'brushed',frameRoughness:.16,frameTextureStrength:.5, surface:'brushed', faceSurface:'grain', textureStrength:.5, faceRoughness:.32, motionBlur:.02, curvature: .18, relief: .045, metal: 'gold', thickness: .16, rim: .08, roughness: .16, face: '#142c59', scale: 1, x: 0, y: 0, rotation: 0, light: 1, title: 'JUGADOR', number: '12' };
function Range({ label, value, min, max, step, onChange }: { label:string; value:number; min:number; max:number; step:number; onChange:(n:number)=>void }) {
  const [active,setActive]=useState(false);
  return <div className={'range '+(active?'is-adjusting':'')}><div><span>{label}</span><output>{value.toFixed((String(step).split('.')[1]||'').length)}</output></div><input className="range-input" type="range" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setActive(true);}} onPointerUp={()=>setActive(false)} onPointerCancel={()=>setActive(false)} onLostPointerCapture={()=>setActive(false)} onBlur={()=>setActive(false)} aria-label={label} value={value} min={min} max={max} step={step} onChange={e=>onChange(e.currentTarget.valueAsNumber)} /></div>;
}
function SurfaceChoice({label,value,onChange}:{label:string;value:Surface;onChange:(s:Surface)=>void}){return <div className="surface-choice"><span>{label}</span><Select value={value} items={Object.entries(surfaceNames).map(([value,label])=>({value,label}))} onValueChange={v=>{if(v)onChange(v as Surface);}}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{Object.entries(surfaceNames).map(([key,name])=><SelectItem key={key} value={key}>{name}</SelectItem>)}</SelectContent></Select></div>;}
function TargetControls({pick,settings,onSettings,layer,onLayer,onClose}:{pick:BadgePick;settings:BadgeSettings;onSettings:(patch:Partial<BadgeSettings>)=>void;layer?:ReliefLayer;onLayer:(patch:Partial<ReliefLayer>)=>void;onClose:()=>void}){
 const frame=pick.kind==='frame',face=pick.kind==='face';
 const surface=layer?layer.surface:face?settings.faceSurface:frame?settings.frameSurface:settings.surface;
 const roughness=layer?layer.roughness:face?settings.faceRoughness:frame?settings.frameRoughness:settings.roughness;
 const strength=layer?layer.textureStrength:face?settings.faceTextureStrength:frame?settings.frameTextureStrength:settings.textureStrength;
 return <div className="target-controls"><div className="target-title"><div><span className="eyebrow">{layer?'GRUPO':'SELECCIÓN'}</span><h2>{pick.label}</h2></div><Button variant="ghost" aria-label="Cerrar selección" onClick={onClose}>×</Button></div>
 {layer?<><label className="color-row">Color<input aria-label={'Color de '+layer.name} type="color" value={layer.color} onChange={e=>onLayer({color:e.target.value})}/></label><Button className="example-button" variant="outline" aria-pressed={layer.metallic} onClick={()=>onLayer({metallic:!layer.metallic})}>{layer.metallic?'Metal':'Esmalte'}</Button></>:face?<label className="color-row">Color del esmalte<input aria-label="Color del esmalte seleccionado" type="color" value={settings.face} onChange={e=>onSettings({face:e.target.value})}/></label>:<div className="metals" role="group" aria-label="Material de la pieza">{(['gold','silver','black'] as const).map((m,i)=><Button variant="outline" key={m} aria-pressed={(frame?settings.frameMetal:settings.metal)===m} className={(frame?settings.frameMetal:settings.metal)===m?'selected':''} onClick={()=>onSettings(frame?{frameMetal:m}:{metal:m})}><i className={'swatch '+m}/>{['Oro','Cromo','Oscuro'][i]}</Button>)}</div>}
 <SurfaceChoice label="Acabado" value={surface} onChange={v=>layer?onLayer({surface:v}):onSettings(face?{faceSurface:v}:frame?{frameSurface:v}:{surface:v})}/>
 <Range label="Rugosidad" value={roughness} min={.04} max={.9} step={.01} onChange={v=>layer?onLayer({roughness:v}):onSettings(face?{faceRoughness:v}:frame?{frameRoughness:v}:{roughness:v})}/>
 <p className="control-hint">Pulido a la izquierda · mate a la derecha</p>
 <details className="advanced-controls"><summary>Detalle y relieve</summary>
 <Range label="Intensidad del acabado" value={strength} min={0} max={1.5} step={.05} onChange={v=>layer?onLayer({textureStrength:v}):onSettings(face?{faceTextureStrength:v}:frame?{frameTextureStrength:v}:{textureStrength:v})}/>
 {layer?<Range label="Altura del grupo" value={layer.height} min={.2} max={3} step={.1} onChange={v=>onLayer({height:v})}/>:frame?<Range label="Ancho del marco" value={settings.rim} min={.035} max={.16} step={.005} onChange={v=>onSettings({rim:v})}/>:!face?<><Range label="Espesor" value={settings.thickness} min={.06} max={.4} step={.01} onChange={v=>onSettings({thickness:v})}/><Range label="Curvatura" value={settings.curvature} min={-.45} max={.45} step={.01} onChange={v=>onSettings({curvature:v})}/></>:null}
 </details></div>;
}
export default function Editor() {
  const baseFile=useRef<HTMLInputElement>(null);const [baseName,setBaseName]=useState('Escudo Boca');
  const panelRef=useRef<HTMLElement>(null);
  const host=useRef<HTMLDivElement>(null), engine=useRef<BadgeEngine|null>(null), file=useRef<HTMLInputElement>(null);
  const [settings,setSettings]=useState(initial), [ready,setReady]=useState(false), [error,setError]=useState(''), [filename,setFilename]=useState(''), [busy,setBusy]=useState(false), [status,setStatus]=useState('');
  const [desktopMode,setMode]=useState<'panel'|'floating'>('floating'),[picked,setPicked]=useState<BadgePick|null>(null),[showGeneral,setShowGeneral]=useState(false);
  const [mobile,setMobile]=useState(false);
  useEffect(()=>{const query=window.matchMedia('(max-width:760px)');const sync=()=>setMobile(query.matches);sync();query.addEventListener('change',sync);return()=>query.removeEventListener('change',sync);},[]);
  const mode=mobile?'floating':desktopMode;
  const [peek,setPeek]=useState(false),[inspectorTab,setInspectorTab]=useState<'properties'|'textures'>('properties');
  const [generalTab,setGeneralTab]=useState<'base'|'design'|'settings'>('base');
  useEffect(()=>{setPeek(false);setInspectorTab('properties');},[picked?.id,showGeneral,generalTab,mobile]);
  const [materials,setMaterials]=useState<Record<string,MaterialUI>>({});
  const [motionOptions,setMotionOptions]=useState(defaultMotion),[motionState,setMotionState]=useState('idle'),[recording,setRecording]=useState(false),[progress,setProgress]=useState(0);
  const [layers,setLayers]=useState<ReliefLayer[]>([]);
  useEffect(()=>{if(picked&&panelRef.current)panelRef.current.scrollTop=0;},[picked]);
  const current=useRef(settings); current.current=settings;
  const set=<K extends keyof BadgeSettings>(key:K,value:BadgeSettings[K])=>setSettings(s=>({...s,[key]:value}));
  useEffect(()=>{ let cancelled=false; let instance:BadgeEngine|undefined;
    import('@/lib/badge-engine').then(async ({BadgeEngine})=>{ if(cancelled||!host.current)return; instance=new BadgeEngine(host.current); await instance.init(); if(cancelled){instance.dispose();return;} engine.current=instance;instance.onMotionState=setMotionState;instance.onSelect=pick=>{setPicked(pick);setShowGeneral(false);}; instance.update(current.current); setReady(true); }).catch(e=>{if(!cancelled)setError('No pudimos iniciar el visor 3D. Probá recargar con WebGL habilitado.'); console.error(e);});
    return ()=>{cancelled=true;if(instance)instance.onSelect=undefined; instance?.dispose(); engine.current=null;};
  },[]);
  useEffect(()=>{engine.current?.update(settings);},[settings]);
  useEffect(()=>{
    const context=(document as Document & {modelContext?:{registerTool:(tool:object,options:{signal:AbortSignal})=>unknown}}).modelContext;
    if(!context?.registerTool)return;
    const lifecycle=new AbortController();
    try{Promise.resolve(context.registerTool({name:'configure_badge_finish',description:'Set the metal finish of the current badge and update the visible editor.',inputSchema:{type:'object',properties:{metal:{type:'string',enum:['gold','silver','black']}},required:['metal'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const data=input as {metal?:unknown};if(!data||!['gold','silver','black'].includes(String(data.metal)))throw Error('Invalid metal');const metal=data.metal as BadgeSettings['metal'];setSettings(s=>({...s,metal}));await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {metal};}},{signal:lifecycle.signal})).catch(console.error);}catch(e){console.error(e);}return()=>lifecycle.abort();
  },[]);
  async function uploadBase(f?:File){if(!f)return;try{if(f.size>512000)throw Error('La base SVG debe pesar menos de 500 KB.');engine.current!.setBaseSVG(await f.text());setBaseName(f.name);setStatus('Nueva base aplicada. Revisá la posición de la ilustración.');}catch(e){setError(e instanceof Error?e.message:'No pudimos cargar la base.');}}
  async function upload(f?:File){ if(!f)return; setError(''); if(f.size>10*1024*1024){setError('La imagen debe pesar menos de 10 MB.');return;} if(!['image/png','image/jpeg','image/webp','image/svg+xml'].includes(f.type)){setError('Elegí PNG, JPG, WebP o SVG.');return;} try{if(f.type==='image/svg+xml'){setMaterials(m=>Object.fromEntries(Object.entries(m).filter(([k])=>['body','frame','face'].includes(k))));const next=engine.current!.setSVG(await f.text());setLayers(next);}else{await engine.current?.setImage(f);setLayers([]);}setFilename(f.name);setGeneralTab('design');setShowGeneral(true);setStatus('Diseño aplicado al interior.');}catch(e){setError(e instanceof Error?e.message:'No pudimos leer el archivo.');} }
  async function example(){try{const response=await fetch('/illustrations.svg');if(!response.ok)throw Error('No pudimos cargar el ejemplo.');setMaterials(m=>Object.fromEntries(Object.entries(m).filter(([k])=>['body','frame','face'].includes(k))));const next=engine.current!.setSVG(await response.text());setLayers(next);setFilename('Cornetas y estrellas');setGeneralTab('design');setShowGeneral(true);setSettings(s=>({...s,scale:1,x:0,y:0,rotation:0,face:'#52647c'}));setStatus('SVG convertido a relieve. Editá sus materiales por grupo.');}catch(e){setError(e instanceof Error?e.message:'No pudimos abrir el ejemplo.');}}
  function layerChange(id:string,change:Partial<ReliefLayer>){engine.current?.setLayer(id,change);setLayers(ls=>ls.map(l=>l.id===id?{...l,...change}:l));}
  async function download(kind:'png'|'glb'){setBusy(true);setError('');try{await engine.current?.download(kind);setStatus(kind==='png'?'PNG transparente descargado.':'Modelo GLB descargado.');}catch{setError('La exportación falló. Volvé a intentarlo.');}finally{setBusy(false);}}
  function captureProject(meta:ProjectMeta):BadgeProject{const e=engine.current!;const scene=e.snapshot();return {format:'badge-studio',version:1,...meta,updatedAt:new Date().toISOString(),thumbnail:e.thumbnail(),scene,motion:{...motionOptions},labels:{base:baseName,design:filename}};}
  async function restoreProject(p:BadgeProject){await engine.current!.restoreSnapshot(p.scene);setSettings({...p.scene.settings});setLayers(p.scene.layers.map(l=>({...l})));setBaseName(p.labels.base);setFilename(p.labels.design);setMotionOptions({...p.motion});setMaterials(Object.fromEntries(Object.entries(p.scene.maps).map(([id,m])=>[id,{...m.settings,label:'Material del proyecto',files:Object.fromEntries(Object.keys(m.images).map(k=>[k,'Incluido en el proyecto']))}])));setPicked(null);setShowGeneral(false);setError('');setStatus('Proyecto abierto. Todos sus elementos siguen siendo editables.');}
  const clearSelection=()=>engine.current?.select(null);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='Escape')engine.current?.select(null);};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
  const targets:BadgePick[]=[{kind:'body',id:'body',label:'Chapa · laterales y reverso',clientX:0,clientY:0},{kind:'frame',id:'frame',label:'Marco metálico',clientX:0,clientY:0},{kind:'face',id:'face',label:'Esmalte interior',clientX:0,clientY:0},...layers.map(l=>({kind:'layer' as const,id:l.id,label:l.name,clientX:0,clientY:0}))];
  const materialPanel=(id:string)=><MaterialControls key={id} id={id} engine={engine.current} value={materials[id]||emptyMaterial} onChange={v=>setMaterials(m=>({...m,[id]:v}))}/>;
  async function exportVideo(){if(!engine.current||recording)return;setRecording(true);setBusy(true);setProgress(0);setError('');try{await engine.current.downloadVideo(motionOptions,setProgress);setStatus('Video descargado.');}catch(e){if(e instanceof DOMException&&e.name==='AbortError')setStatus('Grabación cancelada.');else setError(e instanceof Error?e.message:'Falló el video.');}finally{setRecording(false);setBusy(false);}}
  const inspector=picked?<><div className="inspector-tabs" role="group" aria-label="Controles de la selección"><Button variant="ghost" aria-pressed={inspectorTab==='properties'} onClick={()=>setInspectorTab('properties')}>Pieza</Button><Button variant="ghost" aria-pressed={inspectorTab==='textures'} onClick={()=>setInspectorTab('textures')}>Texturas</Button></div>{inspectorTab==='properties'?<TargetControls pick={picked} settings={settings} onSettings={patch=>setSettings(s=>({...s,...patch}))} layer={layers.find(l=>l.id===picked.id)} onLayer={patch=>layerChange(picked.id,patch)} onClose={clearSelection}/>:<><div className="target-title"><h2>{picked.label}</h2><Button variant="ghost" aria-label="Cerrar selección" onClick={clearSelection}>×</Button></div>{materialPanel(picked.id)}</>}</>:null;

  function openGeneral(tab:'base'|'design'|'settings'){clearSelection();setGeneralTab(tab);setShowGeneral(true);}
  const generalControls=(<div className={"general-controls tab-"+generalTab}><div className="panel-heading"><span className="eyebrow">TU BADGE</span><h1>Tu pieza.</h1><p>Material, forma y detalle.</p></div>
      <section><div className="section-title"><span>01</span><h2>La base</h2></div><div className="base-choice"><Shield/><div><strong>{baseName}</strong><small>Contorno de la chapa</small></div><span className="dot"/></div><input ref={baseFile} type="file" accept=".svg,image/svg+xml" hidden onChange={e=>{uploadBase(e.target.files?.[0]);e.target.value='';}}/><Button className="example-button" variant="outline" disabled={!ready} onClick={()=>baseFile.current?.click()}>Cambiar base · SVG</Button>{baseName!=='Escudo Boca'&&<Button variant="ghost" onClick={()=>{engine.current?.resetBase();setBaseName('Escudo Boca');}}>Volver a Boca</Button>}<p className="control-hint">Se usa el contorno cerrado más grande, sin perforaciones internas.</p><Range label="Espesor" value={settings.thickness} min={.06} max={.4} step={.01} onChange={v=>set('thickness',v)}/><Range label="Ancho del marco" value={settings.rim} min={.035} max={.16} step={.005} onChange={v=>set('rim',v)}/><Range label="Curvatura" value={settings.curvature} min={-.45} max={.45} step={.01} onChange={v=>set('curvature',v)}/><p className="control-hint">− Cóncavo · 0 Plano · + Convexo</p></section>
      <section><div className="section-title"><span>02</span><h2>El acabado</h2></div><details className="material-disclosure"><summary>Texturas de la chapa</summary>{materialPanel('body')}</details><div className="metals" role="group" aria-label="Material de la chapa">{(['gold','silver','black'] as const).map((m,i)=><Button key={m} variant="outline" className={settings.metal===m?'selected':''} aria-pressed={settings.metal===m} onClick={()=>set('metal',m)}><i className={'swatch '+m}/>{['Oro','Cromo','Oscuro'][i]}</Button>)}</div><Range label="Rugosidad" value={settings.roughness} min={.04} max={.65} step={.01} onChange={v=>set('roughness',v)}/><label className="color-row">Esmalte interior<input aria-label="Color del esmalte" type="color" value={settings.face} onChange={e=>set('face',e.target.value)}/></label><SurfaceChoice label="Textura de la chapa" value={settings.surface} onChange={v=>set('surface',v)}/><SurfaceChoice label="Textura del esmalte" value={settings.faceSurface} onChange={v=>set('faceSurface',v)}/><Range label="Intensidad de textura" value={settings.textureStrength} min={0} max={1.5} step={.05} onChange={v=>set('textureStrength',v)}/><Range label="Intensidad de textura · esmalte" value={settings.faceTextureStrength} min={0} max={1.5} step={.05} onChange={v=>set('faceTextureStrength',v)}/><Range label="Rugosidad del esmalte" value={settings.faceRoughness} min={.05} max={.9} step={.05} onChange={v=>set('faceRoughness',v)}/><p className="control-hint">Menos rugosidad: más brillo. Más rugosidad: acabado mate.</p><Range label="Intensidad de luz" value={settings.light} min={.3} max={2} step={.05} onChange={v=>set('light',v)}/></section>
      <section><div className="section-title"><span>03</span><h2>El diseño</h2></div><input ref={file} type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" hidden onChange={e=>{upload(e.target.files?.[0]);e.target.value='';}}/><Button className="upload" variant="outline" disabled={!ready} onClick={()=>file.current?.click()}><Upload size={18}/>{filename?'Cambiar diseño':'Subir diseño'}<small>PNG, JPG, WebP o SVG · hasta 10 MB</small></Button>
      <Button variant="outline" className="example-button" disabled={!ready} onClick={example}>Cargar cornetas en relieve</Button>
      {filename?<div className="file-row"><span>{filename}</span><Button variant="ghost" onClick={()=>{engine.current?.clearImage();setFilename('');setLayers([]);}}>Quitar</Button></div>:<div className="sample-fields"><label>Texto<input maxLength={24} value={settings.title} onChange={e=>set('title',e.target.value)}/></label><label>Número<input maxLength={4} value={settings.number} onChange={e=>set('number',e.target.value)}/></label></div>}
      {layers.length>0&&<div className="layer-list"><Range label="Altura del relieve" value={settings.relief} min={.015} max={.12} step={.005} onChange={v=>set('relief',v)}/><p className="control-hint">{layers.length} grupos · volumen real</p><Accordion>{layers.map(l=><AccordionItem key={l.id} value={l.id}><AccordionTrigger><span className="layer-heading"><i style={{background:l.color}}/>{l.name}<small>{l.height.toFixed(1)}×</small></span></AccordionTrigger><AccordionContent><div className="layer-item"><label><input type="color" aria-label={'Color de '+l.name} value={l.color} onChange={e=>layerChange(l.id,{color:e.target.value})}/><span>Color</span></label><Button variant="outline" aria-pressed={l.metallic} onClick={()=>layerChange(l.id,{metallic:!l.metallic})}>{l.metallic?'Metal':'Esmalte'}</Button></div><Range label={'Altura · '+l.name} value={l.height} min={.2} max={3} step={.1} onChange={v=>layerChange(l.id,{height:v})}/><SurfaceChoice label={'Textura · '+l.name} value={l.surface} onChange={v=>layerChange(l.id,{surface:v})}/><Range label={'Textura · intensidad · '+l.name} value={l.textureStrength} min={0} max={1.5} step={.05} onChange={v=>layerChange(l.id,{textureStrength:v})}/><Range label={'Rugosidad · '+l.name} value={l.roughness} min={.05} max={.9} step={.05} onChange={v=>layerChange(l.id,{roughness:v})}/></AccordionContent></AccordionItem>)}</Accordion></div>}
      <Range label="Escala del diseño" value={settings.scale} min={.25} max={2.5} step={.05} onChange={v=>set('scale',v)}/><Range label="Horizontal" value={settings.x} min={-70} max={70} step={1} onChange={v=>set('x',v)}/><Range label="Vertical" value={settings.y} min={-70} max={70} step={1} onChange={v=>set('y',v)}/><Range label="Rotación" value={settings.rotation} min={-180} max={180} step={1} onChange={v=>set('rotation',v)}/></section><section><div className="section-title"><span>04</span><h2>El movimiento</h2></div><MovementControls value={motionOptions} onChange={setMotionOptions} state={motionState} onPlay={()=>engine.current?.playMotion(motionOptions)} onPause={()=>engine.current?.pauseMotion()} onStop={()=>engine.current?.stopMotion()} onRecord={exportVideo} recording={recording} progress={progress} onCancel={()=>engine.current?.cancelVideo()}/><Range label="Desenfoque al girar" value={settings.motionBlur} min={0} max={.05} step={.01} onChange={v=>set('motionBlur',v)}/><p className="control-hint">0: desactivado. Se aplica sólo mientras girás. El PNG se exporta nítido.</p></section><Button variant="ghost" onClick={()=>{Object.keys(materials).forEach(id=>engine.current?.clearMaps(id));setMaterials({});setSettings(initial);engine.current?.clearImage();setFilename('');setLayers([]);engine.current?.resetView();}}>Restablecer badge</Button>
    </div>);
  const closeEditor=()=>{clearSelection();setShowGeneral(false);setPeek(false);host.current?.focus({preventScroll:true});};
  return <main className={"studio "+(peek?'previewing ':'')+(mode==='floating'?'floating-mode ':'')+(showGeneral?'show-general ':'')+((picked||(mode==='floating'&&showGeneral))?'has-selection':'')}>
    {recording&&<div className="recording-lock"><strong>Grabando video · {Math.round(progress*100)}%</strong><progress value={progress} max="1"/><Button onClick={()=>engine.current?.cancelVideo()}>Cancelar</Button></div>}<header className="topbar" inert={mobile&&!!(picked||showGeneral)}><a className="brand" href="/" aria-label="Badge Studio"><Shield size={25}/><strong>badge<span>studio</span></strong><small>LAB / 01</small></a><div className="interaction-modes" role="group" aria-label="Modo de edición"><Button variant="outline" aria-pressed={mode==='panel'} onClick={()=>{setMode('panel');setShowGeneral(false);}}>Panel</Button><Button variant="outline" aria-pressed={mode==='floating'} onClick={()=>{setMode('floating');setShowGeneral(false);}}>Canvas</Button></div><div className="export"><ProjectLibrary disabled={!ready||busy} capture={captureProject} restore={restoreProject} onShow={()=>engine.current?.stopMotion()}/><Button variant="outline" disabled={!ready||busy} onClick={()=>download('glb')}>GLB</Button><Button disabled={!ready||busy} onClick={()=>download('png')}><Download size={16}/>{busy?'Exportando…':'PNG'}</Button></div></header>
    <aside className="panel" ref={panelRef}>{mode==='panel'?(picked?inspector:generalControls):null}</aside>
    <div className="workspace"><div className="canvas-top"><div className="pick-toolbar"><Select value={picked?.id||''} items={targets.map(t=>({value:t.id,label:t.label}))} onValueChange={id=>{const t=targets.find(t=>t.id===id);if(t)engine.current?.select({...t,clientX:window.innerWidth*.55,clientY:120});}}><SelectTrigger aria-label="Seleccionar pieza" disabled={!ready}><SelectValue placeholder="Seleccionar pieza…"/></SelectTrigger><SelectContent>{targets.map(t=><SelectItem key={t.id} value={t.id}>{t.label}</SelectItem>)}</SelectContent></Select><span className="pick-hint">Tocá una pieza para editarla</span></div><div className="global-actions"><Button variant="outline" onClick={()=>openGeneral('base')}>Base</Button><Button variant="outline" onClick={()=>openGeneral('design')}>Diseño completo</Button><Button variant="outline" onClick={()=>openGeneral('settings')}>Acabado y movimiento</Button></div></div><div ref={host} className="viewport" tabIndex={0} aria-label="Vista interactiva del badge. Arrastrá para rotar y usá la rueda para acercarte."/>{mode==='floating'&&(picked||showGeneral)&&<div className="floating-inspector" role="region" aria-label={picked?'Editar '+picked.label:'Editar badge'}><div className="mobile-inspector-bar"><span>EDITAR BADGE</span><Button variant="outline" aria-pressed={peek} onClick={()=>setPeek(v=>!v)}>{peek?'Volver a editar':'Ver objeto'}</Button><Button onClick={closeEditor}>Listo</Button></div><div className="inspector-content" inert={peek}>{picked?inspector:<><div className="target-title"><h2>{generalTab==='base'?'La base':generalTab==='design'?'Diseño completo':'Acabado y movimiento'}</h2><Button variant="ghost" aria-label="Cerrar ajustes" onClick={()=>setShowGeneral(false)}>×</Button></div>{generalControls}</>}</div></div>}{!ready&&!error&&<div className="loading">Preparando tu chapa…</div>}<div className="canvas-bottom"><span><Move3d size={17}/>Clic: editar · arrastrar: girar · scroll: zoom</span><Button variant="outline" onClick={()=>engine.current?.resetView()} disabled={!ready}><RotateCcw size={15}/>Centrar</Button></div><div className="workspace-note"><ImagePlus size={18}/><span>{layers.length?'SVG con volumen y materiales editables.':'Tu diseño se imprime dentro del marco.'}<br/><strong>{layers.length?'La ilustración acompaña la curvatura.':'El metal queda a la vista.'}</strong></span><span className="format">PNG TRANSPARENTE<br/>2048 × 2048</span></div></div>
    {(error||status)&&<div className={'notice '+(error?'error':'')} role={error?'alert':'status'}>{error||status}<button aria-label="Cerrar aviso" onClick={()=>{setError('');setStatus('');}}>×</button></div>}
  </main>;
}
