'use client';
import {useEffect,useRef,useState} from 'react';
import {FolderOpen,Upload,Download,Copy,Plus,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {copyProject,parseProject,serializeProject,projectStore,collectionStore,readLibrary,MAX_PROJECT_BYTES,type BadgeProject} from '@/lib/projects';
import {collectionPiece,type BadgeCollection} from '@/lib/project-storage';
import './projects.css';
export type ProjectMeta=Pick<BadgeProject,'id'|'name'|'system'|'kind'|'sourceTemplate'|'collectionId'>;
export function downloadProject(project:BadgeProject){const blob=new Blob([serializeProject(project)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(project.name.replace(/[^\p{L}\p{N} _-]/gu,'').trim()||'badge')+'.badge';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
export function ProjectLibrary({disabled,capture,restore,onShow}:{disabled:boolean;capture:(meta:ProjectMeta)=>BadgeProject;restore:(project:BadgeProject)=>Promise<void>;onShow:()=>void}){
 const [open,setOpen]=useState(false),[items,setItems]=useState<BadgeProject[]>([]),[active,setActive]=useState<ProjectMeta|null>(null);
 const [name,setName]=useState('Mi badge'),[destination,setDestination]=useState(''),[filter,setFilter]=useState('collections'),[query,setQuery]=useState('');
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const [pending,setPending]=useState<BadgeProject|null>(null),[deleting,setDeleting]=useState<string|null>(null),[renaming,setRenaming]=useState<string|null>(null),[newName,setNewName]=useState('');
 const [collections,setCollections]=useState<BadgeCollection[]>([]),[folder,setFolder]=useState<string|null>(null),[creating,setCreating]=useState(false),[collectionName,setCollectionName]=useState(''),[templateId,setTemplateId]=useState(''),[renamingFolder,setRenamingFolder]=useState(false);
 const file=useRef<HTMLInputElement>(null);
 const refresh=async()=>{const data=await readLibrary();setItems(data.projects.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)));setCollections(data.collections);};
 const run=async(job:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await job();}catch(e){setError(e instanceof Error?e.message:'No pudimos completar la operación.');}finally{setBusy(false);}};
 useEffect(()=>{if(open)void run(refresh);},[open]);
 function metadata(kind=active?.kind||'piece',fresh=false):ProjectMeta{return {id:!fresh&&active?active.id:crypto.randomUUID(),name:name.trim()||'Mi badge',system:kind==='piece'?(collections.find(c=>c.id===destination)?.name||''):'',collectionId:kind==='piece'?(destination||null):null,kind,sourceTemplate:active?.kind==='template'&&fresh?active.id:active?.sourceTemplate||null};}
 async function save(asTemplate=false){const meta=metadata(asTemplate?'template':active?.kind||'piece',asTemplate),p=capture(meta);serializeProject(p);await projectStore.put(p);setActive(meta);if(asTemplate)setDestination('');await refresh();setMessage(asTemplate?'Plantilla guardada. Usala para crear variantes.':(meta.kind==='template'?'Plantilla actualizada.':meta.collectionId?'Pieza guardada en '+meta.system+'.':'Pieza guardada sin colección.'));return p;}
 async function load(p:BadgeProject,saveFirst=false){if(saveFirst){const saved=await save();if(saved.id===p.id)p=saved;}const next=p.kind==='template'?copyProject(p,'piece'):p;await restore(next);setActive(next);setName(next.name);setDestination(next.collectionId||'');setPending(null);setOpen(false);}
 async function importFile(f:File){if(f.size>MAX_PROJECT_BYTES)throw Error('El proyecto supera el límite de 100 MB.');const imported=parseProject(await f.text());const p={...imported,id:crypto.randomUUID(),collectionId:imported.kind==='piece'?(destination||null):null,system:collections.find(c=>c.id===destination)?.name||'',updatedAt:new Date().toISOString()};await projectStore.put(p);await refresh();setFilter(p.kind==='template'?'template':'piece');setFolder(p.collectionId);setQuery('');setMessage('Proyecto importado. Elegí Abrir o Crear variante en su tarjeta.');}
 const currentFolder=collections.find(c=>c.id===folder);
 const templates=items.filter(p=>p.kind==='template');
 const visible=items.filter(p=>(folder?p.kind==='piece'&&p.collectionId===folder:filter==='template'?p.kind==='template':filter==='piece'?p.kind==='piece'&&!p.collectionId:false)&&p.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const templateOptions=<><option value="">Elegir plantilla…</option>{templates.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</>;
 async function createCollection(){const template=templates.find(p=>p.id===templateId);if(!template)throw Error('Elegí una plantilla.');const c=await collectionStore.create(collectionName,template);await refresh();setFolder(c.id);setCreating(false);setQuery('');setMessage('Colección creada. Agregá su primera pieza desde la plantilla.');}
 async function movePiece(p:BadgeProject,to:string){await collectionStore.move(p.id,to||null);if(active?.id===p.id){setActive({...active,collectionId:to||null,system:collections.find(c=>c.id===to)?.name||''});setDestination(to);}await refresh();setMessage('Pieza movida. Su diseño se conserva.');}

 return <><Button className="library-trigger" variant="outline" disabled={disabled} aria-label="Mis badges" onClick={()=>{onShow();setOpen(true);}}><FolderOpen size={17}/><span>Mis badges</span></Button>
 <Dialog open={open} onOpenChange={v=>{if(!busy){setOpen(v);setPending(null);setDeleting(null);setRenaming(null);}}}><DialogContent className="project-library" showCloseButton={false}>
 <div className="library-heading"><div><span className="eyebrow">TU BIBLIOTECA</span><DialogTitle>Mis badges</DialogTitle><DialogDescription>Piezas y plantillas, guardadas en este navegador.</DialogDescription></div><Button variant="ghost" disabled={busy} aria-label="Cerrar biblioteca" onClick={()=>{setOpen(false);setPending(null);setDeleting(null);setRenaming(null);}}><X size={20}/></Button></div>
 <fieldset disabled={busy} className="library-body">
 <section className="project-current"><div><span className="eyebrow">EN EL CANVAS{active?.kind==='template'?' · PLANTILLA':''}</span><p>Guardá la pieza completa o convertí su estilo en un punto de partida.</p></div><div className="project-fields"><label>Nombre<input value={name} maxLength={100} onChange={e=>setName(e.target.value)}/></label><label>Guardar en<select aria-label="Destino de guardado" value={destination} disabled={active?.kind==='template'} onChange={e=>setDestination(e.target.value)}><option value="">{active?.kind==='template'?'Plantillas':'Piezas sin colección'}</option>{collections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><div className="project-actions"><Button onClick={()=>void run(async()=>{await save();})}>{active?.kind==='template'?'Guardar plantilla':destination?'Guardar en '+(collections.find(c=>c.id===destination)?.name||'colección'):'Guardar pieza'}</Button><Button variant="outline" onClick={()=>void run(async()=>{await save(true);})}><Plus size={15}/>Guardar como plantilla</Button><Button variant="ghost" onClick={()=>void run(async()=>{downloadProject(capture(metadata()));setMessage('Archivo .badge preparado para descargar.');})}><Download size={15}/>Exportar .badge</Button></div></section>
 {pending&&<div className="project-confirm" role="alert"><strong>{pending.kind==='template'?'Crear una variante de':items.some(p=>p.id===pending.id)?'Abrir':'Crear pieza'} «{pending.name}»</strong><p>Esto reemplazará la edición del canvas. Podés guardarla antes de continuar.</p><div className="project-actions"><Button onClick={()=>void run(()=>load(pending,true))}>Guardar actual y abrir</Button><Button variant="outline" onClick={()=>void run(()=>load(pending))}>{items.some(p=>p.id===pending.id)?'Abrir sin guardar':'Crear sin guardar la edición actual'}</Button><Button variant="ghost" onClick={()=>setPending(null)}>Cancelar</Button></div></div>}
 <div className="library-tools"><div className="library-filters" role="group" aria-label="Filtrar biblioteca">{[['collections','Colecciones'],['piece','Sin colección'],['template','Plantillas']].map(([key,label])=><Button key={key} variant="ghost" aria-pressed={!folder&&filter===key} onClick={()=>{setFilter(key);setFolder(null);setQuery('');setCreating(false);}}>{label}</Button>)}</div><Button variant="outline" onClick={()=>file.current?.click()}><Upload size={15}/>Importar .badge</Button><input ref={file} type="file" accept=".badge,application/json" hidden onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void run(()=>importFile(f));}}/></div>
 <input className="library-search" type="search" aria-label="Buscar por nombre" placeholder="Buscar por nombre…" value={query} onChange={e=>setQuery(e.target.value)}/>
 {filter==='collections'&&!folder&&<><div className="collection-heading"><p>Carpetas de piezas creadas a partir de una plantilla.</p><Button variant="outline" onClick={()=>{setCreating(v=>!v);setCollectionName('');setTemplateId('');}}>Nueva colección</Button></div>{creating&&<div className="collection-form"><label>Nombre de la colección<input maxLength={100} value={collectionName} placeholder="Logros 2026" onChange={e=>setCollectionName(e.target.value)}/></label><label>Plantilla base<select value={templateId} onChange={e=>setTemplateId(e.target.value)}>{templateOptions}</select></label>{!templates.length&&<p>Guardá una plantilla con la pieza del canvas para empezar.</p>}<Button disabled={!templates.length} onClick={()=>void run(createCollection)}>Crear colección</Button><Button variant="ghost" onClick={()=>setCreating(false)}>Cancelar</Button></div>}<div className="collection-grid">{collections.filter(c=>c.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(c=><button className="collection-card" key={c.id} onClick={()=>{setFolder(c.id);setQuery('');setRenamingFolder(false);setTemplateId('');}}><FolderOpen size={28}/><strong>{c.name}</strong><span>{items.filter(p=>p.kind==='piece'&&p.collectionId===c.id).length} piezas</span><small>{c.template?'Plantilla: '+c.template.name:'Colección recuperada · elegir plantilla'}</small></button>)}</div>{!collections.length&&!creating&&<p className="library-empty">Creá una colección eligiendo una de tus plantillas.</p>}</>}
 {currentFolder&&<div className="collection-header"><Button variant="ghost" onClick={()=>{setFolder(null);setFilter('collections');setQuery('');}}>← Colecciones</Button><h2>{currentFolder.name}</h2><p>{currentFolder.template?'Plantilla: '+currentFolder.template.name:'Tus piezas anteriores están conservadas. Elegí una plantilla para agregar nuevas.'}</p><div className="project-actions">{currentFolder.template?<Button onClick={()=>setPending(collectionPiece(currentFolder))}><Plus size={16}/>Agregar pieza</Button>:<><select aria-label="Plantilla de la colección recuperada" value={templateId} onChange={e=>setTemplateId(e.target.value)}>{templateOptions}</select><Button disabled={!templateId} onClick={()=>void run(async()=>{const t=templates.find(p=>p.id===templateId);if(t){await collectionStore.setTemplate(currentFolder.id,t);await refresh();}})}>Usar plantilla</Button></>}<Button variant="outline" onClick={()=>{setRenamingFolder(v=>!v);setNewName(currentFolder.name);}}>Renombrar colección</Button></div>{renamingFolder&&<div className="project-rename"><input aria-label="Nombre de la colección" value={newName} maxLength={100} onChange={e=>setNewName(e.target.value)}/><Button onClick={()=>void run(async()=>{await collectionStore.rename(currentFolder.id,newName);setRenamingFolder(false);await refresh();})}>Guardar nombre</Button></div>}<p className="control-hint">Cada pieza es independiente. Agregar usa la plantilla guardada al crear esta colección.</p></div>}
 <div className="project-grid">{visible.map(p=><article className="project-card" key={p.id}><button className="project-preview" aria-label={(p.kind==='template'?'Crear variante de ':'Abrir ')+p.name} onClick={()=>setPending(p)}><img src={p.thumbnail} alt="" loading="lazy"/><span>{p.kind==='template'?'PLANTILLA':'PIEZA'}</span></button><div className="project-card-info"><h3>{p.name}</h3><p>{p.kind==='template'?'Plantilla reutilizable':collections.find(c=>c.id===p.collectionId)?.name||'Sin colección'}</p>{p.kind==='piece'&&<label className="move-piece">Mover a<select aria-label={'Mover '+p.name} value={p.collectionId||''} onChange={e=>void run(()=>movePiece(p,e.target.value))}><option value="">Sin colección</option>{collections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}{renaming===p.id?<div className="project-rename"><input aria-label="Nuevo nombre" maxLength={100} value={newName} onChange={e=>setNewName(e.target.value)}/><Button onClick={()=>void run(async()=>{if(!newName.trim())throw Error('Escribí un nombre.');const next={...p,name:newName.trim(),updatedAt:new Date().toISOString()};await projectStore.put(next);if(active?.id===p.id){setActive(next);setName(next.name);}setRenaming(null);await refresh();})}>Guardar nombre</Button><Button variant="ghost" onClick={()=>setRenaming(null)}>Cancelar</Button></div>:<><Button className="project-open" variant="outline" onClick={()=>setPending(p)}>{p.kind==='template'?'Crear variante':'Abrir pieza'}</Button>{p.kind==='template'&&<Button className="project-open" variant="outline" onClick={()=>{setFilter('collections');setFolder(null);setCreating(true);setTemplateId(p.id);setCollectionName('');setQuery('');}}>Crear colección</Button>}<div className="project-secondary"><Button variant="ghost" onClick={()=>void run(async()=>{await projectStore.put(copyProject(p));await refresh();setMessage('Copia independiente creada.');})} aria-label={'Duplicar '+p.name}><Copy size={14}/></Button><Button variant="ghost" onClick={()=>{setRenaming(p.id);setNewName(p.name);}}>Renombrar</Button><Button variant="ghost" onClick={()=>void run(async()=>downloadProject(p))} aria-label={'Exportar '+p.name}><Download size={14}/></Button><Button variant="ghost" onClick={()=>setDeleting(p.id)}>Eliminar</Button></div></>}{deleting===p.id&&<div className="project-delete"><p>¿Eliminar de este navegador?</p><Button variant="outline" onClick={()=>void run(async()=>{await projectStore.remove(p.id);if(active?.id===p.id)setActive(null);setDeleting(null);await refresh();setMessage('Eliminado de la biblioteca.');})}>Eliminar</Button><Button variant="ghost" onClick={()=>setDeleting(null)}>Cancelar</Button></div>}</div></article>)}</div>
 {(!!folder||filter!=='collections')&&!visible.length&&<div className="library-empty"><FolderOpen size={30}/><h3>{folder?'Todavía no hay piezas':items.length?'No hay coincidencias':'Todavía no hay piezas guardadas'}</h3><p>{folder?'Usá Agregar pieza para empezar desde la plantilla. También podés guardar aquí la edición del canvas.':'Guardá una pieza, importá un archivo o creá una plantilla con el canvas.'}</p></div>}
 </fieldset><div className="library-footer"><p>Almacenamiento local, sin sincronización. Exportá un .badge para tener una copia o llevarlo a otro equipo.</p>{busy&&<p role="status">Procesando…</p>}{error&&<p className="library-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</div>
 </DialogContent></Dialog></>;
}
