'use client';
import {useEffect,useRef,useState} from 'react';
import {FolderOpen,Upload,Download,Copy,Plus,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {copyProject,parseProject,serializeProject,projectStore,MAX_PROJECT_BYTES,type BadgeProject} from '@/lib/projects';
import './projects.css';
export type ProjectMeta=Pick<BadgeProject,'id'|'name'|'system'|'kind'|'sourceTemplate'>;
export function downloadProject(project:BadgeProject){const blob=new Blob([serializeProject(project)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(project.name.replace(/[^\p{L}\p{N} _-]/gu,'').trim()||'badge')+'.badge';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
export function ProjectLibrary({disabled,capture,restore,onShow}:{disabled:boolean;capture:(meta:ProjectMeta)=>BadgeProject;restore:(project:BadgeProject)=>Promise<void>;onShow:()=>void}){
 const [open,setOpen]=useState(false),[items,setItems]=useState<BadgeProject[]>([]),[active,setActive]=useState<ProjectMeta|null>(null);
 const [name,setName]=useState('Mi badge'),[system,setSystem]=useState(''),[filter,setFilter]=useState('all'),[query,setQuery]=useState('');
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const [pending,setPending]=useState<BadgeProject|null>(null),[deleting,setDeleting]=useState<string|null>(null),[renaming,setRenaming]=useState<string|null>(null),[newName,setNewName]=useState('');
 const file=useRef<HTMLInputElement>(null);
 const refresh=async()=>setItems((await projectStore.list()).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)));
 const run=async(job:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await job();}catch(e){setError(e instanceof Error?e.message:'No pudimos completar la operación.');}finally{setBusy(false);}};
 useEffect(()=>{if(open)void run(refresh);},[open]);
 function metadata(kind=active?.kind||'piece',fresh=false):ProjectMeta{return {id:!fresh&&active?active.id:crypto.randomUUID(),name:name.trim()||'Mi badge',system:system.trim(),kind,sourceTemplate:active?.kind==='template'&&fresh?active.id:active?.sourceTemplate||null};}
 async function save(asTemplate=false){const meta=metadata(asTemplate?'template':active?.kind||'piece',asTemplate),p=capture(meta);serializeProject(p);await projectStore.put(p);setActive(meta);await refresh();setMessage(asTemplate?'Plantilla guardada. Usala para crear variantes.':'Pieza guardada en este navegador.');return p;}
 async function load(p:BadgeProject,saveFirst=false){if(saveFirst){const saved=await save();if(saved.id===p.id)p=saved;}const next=p.kind==='template'?copyProject(p,'piece'):p;await restore(next);setActive(next);setName(next.name);setSystem(next.system);setPending(null);setOpen(false);}
 async function importFile(f:File){if(f.size>MAX_PROJECT_BYTES)throw Error('El proyecto supera el límite de 100 MB.');const imported=parseProject(await f.text());const p={...imported,id:crypto.randomUUID(),updatedAt:new Date().toISOString()};await projectStore.put(p);await refresh();setFilter('all');setQuery('');setMessage('Proyecto importado. Elegí Abrir o Crear variante en su tarjeta.');}
 const visible=items.filter(p=>(filter==='all'||p.kind===filter)&&`${p.name} ${p.system}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <><Button className="library-trigger" variant="outline" disabled={disabled} aria-label="Mis badges" onClick={()=>{onShow();setOpen(true);}}><FolderOpen size={17}/><span>Mis badges</span></Button>
 <Dialog open={open} onOpenChange={v=>{if(!busy){setOpen(v);setPending(null);setDeleting(null);setRenaming(null);}}}><DialogContent className="project-library" showCloseButton={false}>
 <div className="library-heading"><div><span className="eyebrow">TU BIBLIOTECA</span><DialogTitle>Mis badges</DialogTitle><DialogDescription>Piezas y plantillas, guardadas en este navegador.</DialogDescription></div><Button variant="ghost" disabled={busy} aria-label="Cerrar biblioteca" onClick={()=>{setOpen(false);setPending(null);setDeleting(null);setRenaming(null);}}><X size={20}/></Button></div>
 <fieldset disabled={busy} className="library-body">
 <section className="project-current"><div><span className="eyebrow">EN EL CANVAS{active?.kind==='template'?' · PLANTILLA':''}</span><p>Guardá la pieza completa o convertí su estilo en un punto de partida.</p></div><div className="project-fields"><label>Nombre<input value={name} maxLength={100} onChange={e=>setName(e.target.value)}/></label><label>Sistema o colección <small>Opcional</small><input value={system} maxLength={100} placeholder="Ej. Logros de la temporada" onChange={e=>setSystem(e.target.value)}/></label></div><div className="project-actions"><Button onClick={()=>void run(async()=>{await save();})}>{active?'Guardar cambios':'Guardar pieza'}</Button><Button variant="outline" onClick={()=>void run(async()=>{await save(true);})}><Plus size={15}/>Guardar como plantilla</Button><Button variant="ghost" onClick={()=>void run(async()=>{downloadProject(capture(metadata()));setMessage('Archivo .badge preparado para descargar.');})}><Download size={15}/>Exportar .badge</Button></div></section>
 {pending&&<div className="project-confirm" role="alert"><strong>{pending.kind==='template'?'Crear una variante de':'Abrir'} «{pending.name}»</strong><p>Esto reemplazará la edición del canvas. Podés guardarla antes de continuar.</p><div className="project-actions"><Button onClick={()=>void run(()=>load(pending,true))}>Guardar actual y abrir</Button><Button variant="outline" onClick={()=>void run(()=>load(pending))}>Abrir sin guardar</Button><Button variant="ghost" onClick={()=>setPending(null)}>Cancelar</Button></div></div>}
 <div className="library-tools"><div className="library-filters" role="group" aria-label="Filtrar biblioteca">{[['all','Todo'],['piece','Piezas'],['template','Plantillas']].map(([key,label])=><Button key={key} variant="ghost" aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</Button>)}</div><Button variant="outline" onClick={()=>file.current?.click()}><Upload size={15}/>Importar .badge</Button><input ref={file} type="file" accept=".badge,application/json" hidden onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void run(()=>importFile(f));}}/></div>
 <input className="library-search" type="search" aria-label="Buscar por nombre o sistema" placeholder="Buscar por nombre o sistema…" value={query} onChange={e=>setQuery(e.target.value)}/>
 <div className="project-grid">{visible.map(p=><article className="project-card" key={p.id}><button className="project-preview" aria-label={(p.kind==='template'?'Crear variante de ':'Abrir ')+p.name} onClick={()=>setPending(p)}><img src={p.thumbnail} alt="" loading="lazy"/><span>{p.kind==='template'?'PLANTILLA':'PIEZA'}</span></button><div className="project-card-info"><h3>{p.name}</h3><p>{p.system||'Sin colección'}</p>{renaming===p.id?<div className="project-rename"><input aria-label="Nuevo nombre" maxLength={100} value={newName} onChange={e=>setNewName(e.target.value)}/><Button onClick={()=>void run(async()=>{if(!newName.trim())throw Error('Escribí un nombre.');const next={...p,name:newName.trim(),updatedAt:new Date().toISOString()};await projectStore.put(next);if(active?.id===p.id){setActive(next);setName(next.name);}setRenaming(null);await refresh();})}>Guardar nombre</Button><Button variant="ghost" onClick={()=>setRenaming(null)}>Cancelar</Button></div>:<><Button className="project-open" variant="outline" onClick={()=>setPending(p)}>{p.kind==='template'?'Crear variante':'Abrir pieza'}</Button><div className="project-secondary"><Button variant="ghost" onClick={()=>void run(async()=>{await projectStore.put(copyProject(p));await refresh();setMessage('Copia independiente creada.');})} aria-label={'Duplicar '+p.name}><Copy size={14}/></Button><Button variant="ghost" onClick={()=>{setRenaming(p.id);setNewName(p.name);}}>Renombrar</Button><Button variant="ghost" onClick={()=>void run(async()=>downloadProject(p))} aria-label={'Exportar '+p.name}><Download size={14}/></Button><Button variant="ghost" onClick={()=>setDeleting(p.id)}>Eliminar</Button></div></>}{deleting===p.id&&<div className="project-delete"><p>¿Eliminar de este navegador?</p><Button variant="outline" onClick={()=>void run(async()=>{await projectStore.remove(p.id);if(active?.id===p.id)setActive(null);setDeleting(null);await refresh();setMessage('Eliminado de la biblioteca.');})}>Eliminar</Button><Button variant="ghost" onClick={()=>setDeleting(null)}>Cancelar</Button></div>}</div></article>)}</div>
 {!visible.length&&<div className="library-empty"><FolderOpen size={30}/><h3>{items.length?'No hay coincidencias':'Tu primera colección empieza acá'}</h3><p>{items.length?'Probá con otro nombre o filtro.':'Guardá la pieza del canvas. Una plantilla te permite crear nuevas variantes sin modificar el original.'}</p></div>}
 </fieldset><div className="library-footer"><p>Almacenamiento local, sin sincronización. Exportá un .badge para tener una copia o llevarlo a otro equipo.</p>{busy&&<p role="status">Procesando…</p>}{error&&<p className="library-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</div>
 </DialogContent></Dialog></>;
}
