import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { SVGLoader } from 'three/addons/loaders/SVGLoader.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { GLTFExporter } from 'three/addons/exporters/GLTFExporter.js';
import { parseRelief, bendGeometry, type ReliefLayer, type ReliefPart } from './relief';
import { SurfaceLibrary, type Surface } from './surfaces';
import {parseBaseSVG} from './base-shape';
import {safeFrameDistance} from './framing';
import { MotionPreview } from './motion-preview';
import { pickBadge, isSelectionGesture, surfaceUV, type BadgePick } from './interaction';
export type { BadgePick } from './interaction';
export type { ReliefLayer } from './relief';
export interface BadgeSettings {faceTextureStrength:number;frameMetal:'gold'|'silver'|'black';frameSurface:Surface;frameRoughness:number;frameTextureStrength:number;surface:Surface;faceSurface:Surface;textureStrength:number;faceRoughness:number;motionBlur:number;curvature:number;relief:number;metal:'gold'|'silver'|'black';thickness:number;rim:number;roughness:number;face:string;scale:number;x:number;y:number;rotation:number;light:number;title:string;number:string}
export class BadgeEngine {
  private cameraTween:{start:number;from:THREE.Vector3;to:THREE.Vector3;targetFrom:THREE.Vector3;targetTo:THREE.Vector3}|null=null;
  onSelect?: (pick:BadgePick|null)=>void;
  private selected:BadgePick|null=null; private selectionOutline=new THREE.Group(); private outlineMaterial=new THREE.LineBasicMaterial({color:'#e5f76c',transparent:true,opacity:.9,depthTest:false});
  private down:{x:number;y:number}|null=null; private pointers=new Set<number>();
  private pointerDown=(e:PointerEvent)=>{this.cameraTween=null;if(e.button!==0)return;this.pointers.add(e.pointerId);this.down=this.pointers.size===1?{x:e.clientX,y:e.clientY}:null;};
  private pointerUp=(e:PointerEvent)=>{const start=this.down;const single=this.pointers.size===1;this.pointers.delete(e.pointerId);this.down=null;if(!start||!single||!isSelectionGesture(start,{x:e.clientX,y:e.clientY}))return;const picked=pickBadge(this.camera,this.badge.children,this.renderer.domElement.getBoundingClientRect(),e.clientX,e.clientY);this.select(picked);};
  private pointerCancel=()=>{this.down=null;this.pointers.clear();};
  select(pick:BadgePick|null){this.selected=pick;this.highlight();this.frameBadge();this.onSelect?.(pick);}
  private highlight(){for(const child of [...this.selectionOutline.children]){this.selectionOutline.remove(child);(child as THREE.LineSegments).geometry.dispose();}if(!this.selected)return;for(const obj of this.badge.children){if(obj.userData.pick?.id!==this.selected.id)continue;const mesh=obj as THREE.Mesh;const lines=new THREE.LineSegments(new THREE.EdgesGeometry(mesh.geometry,40),this.outlineMaterial);lines.renderOrder=5;this.selectionOutline.add(lines);}}
  private surfaces=new SurfaceLibrary(); private motion=new MotionPreview(); private previousCamera=new THREE.Vector3(); private exporting=false;
  private parts:ReliefPart[]=[]; private layers:ReliefLayer[]=[]; private reliefMaterials=new Map<string,THREE.MeshStandardMaterial>();
  private scene=new THREE.Scene(); private camera=new THREE.PerspectiveCamera(33,1,.1,100);
  private renderer:THREE.WebGLRenderer; private controls:OrbitControls; private badge=new THREE.Group(); private points:THREE.Vector2[]=[];private bocaPoints:THREE.Vector2[]=[];
  private metal=new THREE.MeshStandardMaterial({metalness:1,roughness:.16});
  private frameMaterial=new THREE.MeshStandardMaterial({metalness:1,roughness:.16});
  private enamel=new THREE.MeshPhysicalMaterial({metalness:.12,roughness:.23,clearcoat:1,clearcoatRoughness:.18});
  private canvas=document.createElement('canvas'); private texture:THREE.CanvasTexture; private image:HTMLImageElement|null=null;
  private settings?:BadgeSettings; private geometryKey=''; private raf=0; private resize:ResizeObserver; private disposed=false; private env?:THREE.WebGLRenderTarget;
  constructor(private host:HTMLElement){
    this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setClearColor(0,0);this.renderer.toneMapping=THREE.ACESFilmicToneMapping;
    host.appendChild(this.renderer.domElement);this.renderer.domElement.addEventListener('pointerdown',this.pointerDown);this.renderer.domElement.addEventListener('pointerup',this.pointerUp);this.renderer.domElement.addEventListener('pointercancel',this.pointerCancel);this.renderer.domElement.style.touchAction='none';
    this.canvas.width=1024;this.canvas.height=1024;this.texture=new THREE.CanvasTexture(this.canvas);this.texture.colorSpace=THREE.SRGBColorSpace;this.enamel.map=this.texture;
    this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.enablePan=false;this.controls.minDistance=4;this.controls.maxDistance=15;this.resetView();
    this.scene.add(this.badge,this.selectionOutline);this.resize=new ResizeObserver(()=>this.fit());this.resize.observe(host);this.fit();
  }
  async init(){const response=await fetch('/escudo.svg');if(!response.ok)throw Error('SVG missing');const svg=await response.text();if(this.disposed)return;
    const parsed=new SVGLoader().parse(svg);this.points=parsed.paths[1].subPaths[0].getPoints(32).map(p=>new THREE.Vector2((p.x-1314)/3139*4,(1569.5-p.y)/3139*4));
    this.bocaPoints=this.points.map(p=>p.clone());
    const room=new RoomEnvironment();const pmrem=new THREE.PMREMGenerator(this.renderer);this.env=pmrem.fromScene(room,.035);this.scene.environment=this.env.texture;room.dispose();pmrem.dispose();this.animate();
  }
  private animate=()=>{if(this.disposed)return;this.previousCamera.copy(this.camera.position);if(this.cameraTween){const t=this.cameraTween,k=Math.min(1,(performance.now()-t.start)/450),ease=1-Math.pow(1-k,3);this.camera.position.lerpVectors(t.from,t.to,ease);this.controls.target.lerpVectors(t.targetFrom,t.targetTo,ease);if(k===1)this.cameraTween=null;}this.controls.update();const delta=this.camera.position.clone().sub(this.previousCamera);const right=new THREE.Vector3().setFromMatrixColumn(this.camera.matrixWorld,0),up=new THREE.Vector3().setFromMatrixColumn(this.camera.matrixWorld,1);const strength=this.settings?.motionBlur||0;const blur=new THREE.Vector2(delta.dot(right),delta.dot(up)).multiplyScalar(strength*.3);blur.clampLength(0,.025);if(!this.exporting)this.motion.render(this.renderer,this.scene,this.camera,blur);this.raf=requestAnimationFrame(this.animate);};
  private fit(){const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.frameBadge();}
  resetView(){this.camera.position.set(2.3,.8,9);this.controls.target.set(0,0,0);this.controls.update();this.frameBadge();}
  private frameBadge(){if(!this.badge.children.length)return;this.badge.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(this.badge),target=bounds.getCenter(new THREE.Vector3());if(this.selected){const picked=new THREE.Box3();for(const mesh of this.badge.children)if(mesh.userData.pick?.id===this.selected.id)picked.expandByObject(mesh);if(!picked.isEmpty())target.lerp(picked.getCenter(new THREE.Vector3()),.12);}const distance=safeFrameDistance(bounds,this.camera.aspect,this.camera.fov,target);this.controls.minDistance=distance;this.controls.maxDistance=Math.max(18,distance*2);const direction=this.camera.position.clone().sub(this.controls.target).normalize();const to=target.clone().addScaledVector(direction,distance*(this.selected?1:1.08));if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){this.camera.position.copy(to);this.controls.target.copy(target);this.controls.update();this.cameraTween=null;return;}this.cameraTween={start:performance.now(),from:this.camera.position.clone(),to,targetFrom:this.controls.target.clone(),targetTo:target};}
  update(s:BadgeSettings){this.settings={...s};if(!this.points.length)return;this.metal.color.set(s.metal==='gold'?'#e8bc69':s.metal==='silver'?'#dbe0e8':'#4b5260');this.metal.roughness=s.roughness;this.scene.environmentIntensity=s.light;this.enamel.roughness=s.faceRoughness;this.enamel.clearcoat=1-s.faceRoughness;this.enamel.clearcoatRoughness=s.faceRoughness;this.surfaces.apply(this.metal,s.surface,s.textureStrength);this.frameMaterial.color.set(s.frameMetal==='gold'?'#e8bc69':s.frameMetal==='silver'?'#dbe0e8':'#4b5260');this.frameMaterial.roughness=s.frameRoughness;this.surfaces.apply(this.frameMaterial,s.frameSurface,s.frameTextureStrength);this.surfaces.apply(this.enamel,s.faceSurface,s.faceTextureStrength);const key=`${s.thickness}-${s.rim}-${s.curvature}-${s.relief}-${this.parts.length ? [s.scale,s.x,s.y,s.rotation].join() : ""}`;if(key!==this.geometryKey){this.geometryKey=key;this.build(s);}this.paint();}
  private build(s:BadgeSettings){for(const obj of [...this.badge.children]){this.badge.remove(obj);(obj as THREE.Mesh).geometry.dispose();}
    const shape=new THREE.Shape(this.points);const options={depth:s.thickness,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.014,bevelThickness:.014,curveSegments:32};
    const body=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,options),this.metal);body.name='Chapa';body.userData.pick={kind:'body',id:'body',label:'Chapa · laterales y reverso'};this.badge.add(body);
    const inner=this.points.map(p=>p.clone().multiplyScalar(1-s.rim));const ring=new THREE.Shape(this.points);ring.holes.push(new THREE.Path([...inner].reverse()));
    const frame=new THREE.Mesh(new THREE.ExtrudeGeometry(ring,{...options,depth:.045,bevelSize:.009,bevelThickness:.009}),this.frameMaterial);frame.position.z=s.thickness;frame.name='Marco';frame.userData.pick={kind:'frame',id:'frame',label:'Marco metálico'};this.badge.add(frame);
    const faceGeometry=new THREE.ShapeGeometry(new THREE.Shape(inner),32);const positions=faceGeometry.getAttribute('position');const uv=faceGeometry.getAttribute('uv');for(let i=0;i<positions.count;i++)uv.setXY(i,(positions.getX(i)+2)/4,(positions.getY(i)+2)/4);uv.needsUpdate=true;
    const face=new THREE.Mesh(faceGeometry,this.enamel);face.position.z=s.thickness+.025;face.name='Esmalte e impresion';face.userData.pick={kind:'face',id:'face',label:'Esmalte interior'};this.badge.add(face);
    const angle=-s.rotation*Math.PI/180;
    for(const part of this.parts){const layer=this.layers.find(l=>l.id===part.layer)!;const g=part.geometry.clone(),p=g.getAttribute('position');for(let i=0;i<p.count;i++){const x=p.getX(i)*s.scale,y=p.getY(i)*s.scale;p.setXYZ(i,x*Math.cos(angle)-y*Math.sin(angle)+s.x*.02,x*Math.sin(angle)+y*Math.cos(angle)-s.y*.02,p.getZ(i)*s.relief*layer.height+s.thickness+.027+part.order*.0015);}g.computeVertexNormals();const mesh=new THREE.Mesh(g,this.reliefMaterials.get(part.layer));mesh.name=part.layer;mesh.userData.pick={kind:'layer',id:part.layer,label:layer.name};this.badge.add(mesh);}
    for(const child of this.badge.children){const mesh=child as THREE.Mesh;mesh.geometry.translate(0,0,mesh.position.z);mesh.position.z=0;mesh.geometry=surfaceUV(mesh.geometry,mesh.userData.pick?.kind==='face');mesh.geometry=bendGeometry(mesh.geometry,s.curvature);}
    this.highlight();this.frameBadge();

  }
  private paint(){const s=this.settings;if(!s)return;const ctx=this.canvas.getContext('2d')!;ctx.fillStyle=s.face;ctx.fillRect(0,0,1024,1024);ctx.save();ctx.translate(512+s.x*5,512+s.y*5);ctx.rotate(s.rotation*Math.PI/180);ctx.scale(s.scale,s.scale);
    if(this.image){const factor=Math.min(820/this.image.naturalWidth,820/this.image.naturalHeight);ctx.drawImage(this.image,-this.image.naturalWidth*factor/2,-this.image.naturalHeight*factor/2,this.image.naturalWidth*factor,this.image.naturalHeight*factor);}
    else if(!this.parts.length){ctx.textAlign='center';ctx.fillStyle='#f3ce79';ctx.font='600 40px sans-serif';ctx.fillText(s.title,0,-210);ctx.font='900 290px sans-serif';ctx.fillText(s.number,0,60);ctx.fillRect(-180,115,360,3);ctx.font='500 23px sans-serif';ctx.fillText('LA BOMBONERA',0,165);ctx.font='400 18px sans-serif';ctx.fillText('BUENOS AIRES · 1905',0,206);}ctx.restore();this.texture.needsUpdate=true;
  }
  setBaseSVG(svg:string){const points=parseBaseSVG(svg);this.points=points;this.select(null);this.geometryKey='';if(this.settings)this.update(this.settings);}
  resetBase(){this.points=this.bocaPoints.map(p=>p.clone());this.select(null);this.geometryKey='';if(this.settings)this.update(this.settings);}
  async setImage(file:File){const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();if(img.naturalWidth*img.naturalHeight>40_000_000)throw Error('Image too large');this.clearRelief();this.image=img;this.geometryKey='';if(this.settings)this.update(this.settings);}finally{URL.revokeObjectURL(url);}}
  clearImage(){this.clearRelief();this.image=null;this.geometryKey='';if(this.settings)this.update(this.settings);}
  private clearRelief(){this.select(null);for(const p of this.parts)p.geometry.dispose();this.parts=[];for(const m of this.reliefMaterials.values())m.dispose();this.reliefMaterials.clear();this.layers=[];}
  setSVG(svg:string){const parsed=parseRelief(svg);this.clearRelief();this.image=null;this.parts=parsed.parts;this.layers=parsed.layers;for(const l of this.layers){const material=new THREE.MeshStandardMaterial({color:l.color,metalness:l.metallic?1:.1,roughness:l.roughness});this.surfaces.apply(material,l.surface,l.textureStrength);this.reliefMaterials.set(l.id,material);}this.geometryKey='';if(this.settings)this.update(this.settings);return this.layers.map(l=>({...l}));}
  setLayer(id:string,changes:Partial<ReliefLayer>){const layer=this.layers.find(l=>l.id===id),m=this.reliefMaterials.get(id);if(!layer||!m)return;Object.assign(layer,changes);m.color.set(layer.color);m.metalness=layer.metallic?1:.1;m.roughness=layer.roughness;this.surfaces.apply(m,layer.surface,layer.textureStrength);if(changes.height!==undefined&&this.settings)this.build(this.settings);}

  async download(kind:'png'|'glb'){let blob:Blob;if(kind==='png'){const old=this.renderer.getSize(new THREE.Vector2()),ratio=this.renderer.getPixelRatio(),aspect=this.camera.aspect;try{this.exporting=true;this.selectionOutline.visible=false;this.renderer.setPixelRatio(1);this.renderer.setSize(2048,2048,false);this.camera.aspect=1;this.camera.updateProjectionMatrix();this.renderer.render(this.scene,this.camera);blob=await new Promise<Blob>((resolve,reject)=>this.renderer.domElement.toBlob(b=>b?resolve(b):reject(Error('PNG failed')),'image/png'));}finally{this.exporting=false;this.selectionOutline.visible=true;this.renderer.setPixelRatio(ratio);this.renderer.setSize(old.x,old.y,false);this.camera.aspect=aspect;this.camera.updateProjectionMatrix();}}else{const result=await new GLTFExporter().parseAsync(this.badge,{binary:true});blob=new Blob([result as ArrayBuffer],{type:'model/gltf-binary'});}const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download=`mi-badge.${kind}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  }
  dispose(){this.disposed=true;this.renderer.domElement.removeEventListener('pointerdown',this.pointerDown);this.renderer.domElement.removeEventListener('pointerup',this.pointerUp);this.renderer.domElement.removeEventListener('pointercancel',this.pointerCancel);this.select(null);this.outlineMaterial.dispose();cancelAnimationFrame(this.raf);this.resize.disconnect();this.controls.dispose();this.badge.traverse(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose();});this.clearRelief();this.metal.dispose();this.frameMaterial.dispose();this.enamel.dispose();this.texture.dispose();this.env?.dispose();this.surfaces.dispose();this.motion.dispose();this.renderer.dispose();this.renderer.domElement.remove();}
}
