import type {BadgeProject} from './projects';
export interface BadgeCollection{id:string;name:string;template:BadgeProject|null;createdAt:string}
function database(){return new Promise<IDBDatabase>((resolve,reject)=>{let blocked=false;const request=indexedDB.open('badge-studio-projects',2);
 request.onupgradeneeded=()=>{const db=request.result,tx=request.transaction!;if(!db.objectStoreNames.contains('projects'))db.createObjectStore('projects',{keyPath:'id'});if(!db.objectStoreNames.contains('collections'))db.createObjectStore('collections',{keyPath:'id'});
 const projects=tx.objectStore('projects'),collections=tx.objectStore('collections'),read=projects.getAll();read.onsuccess=()=>{const all=read.result as BadgeProject[],groups=new Map<string,BadgeCollection>();for(const p of all){if(p.collectionId!==undefined)continue;const name=p.system?.trim();if(p.kind==='piece'&&name){let c=groups.get(name);if(!c){const related=all.filter(x=>x.kind==='piece'&&x.system?.trim()===name),source=related[0]?.sourceTemplate;const template=source&&related.every(x=>x.sourceTemplate===source)?all.find(x=>x.id===source&&x.kind==='template'):null;c={id:crypto.randomUUID(),name,template:template?structuredClone(template):null,createdAt:new Date().toISOString()};groups.set(name,c);collections.put(c);}projects.put({...p,collectionId:c.id});}else projects.put({...p,collectionId:null});}};};
 request.onsuccess=()=>{if(blocked){request.result.close();return;}request.result.onversionchange=()=>request.result.close();resolve(request.result);};request.onerror=()=>reject(Error('No se pudo abrir la biblioteca local. Exportá una copia .badge de tu edición.'));request.onblocked=()=>{blocked=true;reject(Error('Cerrá otras pestañas de Badge Studio y volvé a abrir la biblioteca para actualizarla.'));};});}
async function transact<T>(mode:IDBTransactionMode,run:(p:IDBObjectStore,c:IDBObjectStore,set:(v:T)=>void,fail:(message:string)=>void)=>void){const db=await database();return new Promise<T>((resolve,reject)=>{const tx=db.transaction(['projects','collections'],mode);let result:T,reason='No se pudo guardar el cambio. Puede faltar espacio en el navegador.';const fail=(message:string)=>{reason=message;tx.abort();};tx.oncomplete=()=>{db.close();resolve(result);};tx.onerror=tx.onabort=()=>{db.close();reject(Error(reason));};try{run(tx.objectStore('projects'),tx.objectStore('collections'),v=>{result=v;},fail);}catch(e){reason=e instanceof Error?e.message:reason;tx.abort();}});}
export function readLibrary(){return transact<{projects:BadgeProject[];collections:BadgeCollection[]}>('readonly',(p,c,set)=>{const state={projects:[] as BadgeProject[],collections:[] as BadgeCollection[]};const a=p.getAll(),b=c.getAll();a.onsuccess=()=>{state.projects=a.result;set(state);};b.onsuccess=()=>{state.collections=b.result;set(state);};});}
export const projectStore={list:async()=>(await readLibrary()).projects,put:(item:BadgeProject)=>transact<void>('readwrite',(p,c,_,fail)=>{if(item.kind==='template'||!item.collectionId){p.put({...item,collectionId:null,system:''});return;}const read=c.get(item.collectionId);read.onsuccess=()=>{if(!read.result){fail('La colección ya no existe. Elegí otro destino para guardar.');return;}p.put({...item,system:read.result.name});};}),remove:(id:string)=>transact<void>('readwrite',p=>{p.delete(id);})};
export const collectionStore={
 create:(name:string,template:BadgeProject)=>transact<BadgeCollection>('readwrite',(_,c,set)=>{if(!name.trim()||name.trim().length>100||template.kind!=='template')throw Error('Elegí una plantilla y un nombre de hasta 100 caracteres.');const item:BadgeCollection={id:crypto.randomUUID(),name:name.trim(),template:structuredClone(template),createdAt:new Date().toISOString()};c.add(item);set(item);}),
 rename:(id:string,name:string)=>transact<void>('readwrite',(p,c,_,fail)=>{if(!name.trim()||name.length>100)throw Error('Escribí un nombre de hasta 100 caracteres.');const read=c.get(id);read.onsuccess=()=>{if(!read.result)return fail('La colección ya no existe.');c.put({...read.result,name:name.trim()});const all=p.getAll();all.onsuccess=()=>all.result.filter((x:BadgeProject)=>x.collectionId===id).forEach((x:BadgeProject)=>p.put({...x,system:name.trim()}));};}),
 setTemplate:(id:string,template:BadgeProject)=>transact<void>('readwrite',(_,c,__,fail)=>{if(template.kind!=='template')throw Error('Elegí una plantilla.');const read=c.get(id);read.onsuccess=()=>{if(!read.result)return fail('La colección ya no existe.');c.put({...read.result,template:structuredClone(template)});};}),
 move:(id:string,destination:string|null)=>transact<void>('readwrite',(p,c,_,fail)=>{const read=p.get(id);read.onsuccess=()=>{const item=read.result as BadgeProject;if(!item||item.kind!=='piece')return fail('No encontramos esa pieza.');if(!destination){p.put({...item,collectionId:null,system:''});return;}const target=c.get(destination);target.onsuccess=()=>{if(!target.result)return fail('La colección ya no existe.');p.put({...item,collectionId:destination,system:target.result.name});};};}),
};
export function collectionPiece(c:BadgeCollection):BadgeProject{if(!c.template)throw Error('Elegí una plantilla para agregar nuevas piezas.');return {...structuredClone(c.template),id:crypto.randomUUID(),kind:'piece',name:'Nueva pieza',sourceTemplate:c.template.id,collectionId:c.id,system:c.name,updatedAt:new Date().toISOString()};}
